### ISSUE TITLE
Superstream not working

### ISSUE THREAD

**Issue by TusharCoder-Ing** [flixclusiveorg/flx-providers#36]
### Provider information

Superstream

### Steps to reproduce

1. Click on any movie
2. Click on watch
3. The loading screen appears and then the error appears

### Flixclusive version

2.1.3

### Other details

![1000072803](https://github.com/user-attachments/assets/0c233410-54e7-4d4f-80fa-3d0c5ea65eac)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by TusharCoder-Ing** [comment]
![Screenshot_2024-10-31-22-21-26-602_com flixclusive](https://github.com/user-attachments/assets/abb9add9-923a-4dae-aa8c-ed7f28535fcb)
Issue still persists

**Comment by rhenwinch** [comment]
Fixed on 8e02cf73994aa4a828ae8dcdcce25ebdfdb8b1c4
